#! /bin/sh

sxhkd &

# Monitor setup
bspc monitor HDMI-0 -d main term dev media gimp misc
bspc monitor DVI-D-0 -d misc1 misc2 misc3

# Config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Window rules
bspc rule -a Gimp state=floating follow=on

# Start polybar
polybar example &
